version: '3.3'

networks:
  book_store:
    driver: bridge

services:
  mysql:
    build: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: book_store
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
      #esse comando para inicializar o banco de dados
    command: --init-file /data/application/init.sql
# Names our volume
volumes:
    my-db: 
 
